apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lightrag
  labels:
    app.kubernetes.io/name: lightrag
    app.kubernetes.io/instance: lightrag
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: 'more_set_headers "X-Accel-Buffering: no";'
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: rag-test-01.f123.pub
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lightrag
                port:
                  name: http
