apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lightrag-test-inputs-rwx
spec:
  storageClassName: syno-nfs
  accessModes: [ReadWriteMany]
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lightrag-test-working-rwx
spec:
  storageClassName: syno-nfs
  accessModes: [ReadWriteMany]
  resources:
    requests:
      storage: 40Gi
