labels:
  platform: linux/amd64

when:
  event: [push, pull_request, tag]
  branch: [master]

steps:
  backend:
    image: docker-hub.f123.pub/base/uv:python3.12-bookworm-slim-lightrag-e5b65587bce7@sha256:e5b65587bce7de595f299855d7385fe7fca39b8a74baa261ba1b7147afa78e58
    commands:
      - scripts/ci/backend-check.sh
  frontend:
    image: docker-hub.f123.pub/base/bun:1-lightrag-9114c058aeae@sha256:9114c058aeae42162ee16dd5084b95fe9473970bb6bcb5b232ab1630f0546895
    commands:
      - scripts/ci/frontend-check.sh
  delivery-static:
    image: docker-hub.f123.pub/base/uv:python3.12-bookworm-slim-lightrag-e5b65587bce7@sha256:e5b65587bce7de595f299855d7385fe7fca39b8a74baa261ba1b7147afa78e58
    commands:
      - scripts/ci/delivery-check.sh
